WITH SUB AS(
    SELECT
        ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RATE
    FROM
        ECOLI_DATA 
)

SELECT
    ID,
    CASE
        WHEN RATE <= 0.25 THEN 'CRITICAL'
        WHEN RATE <= 0.5 THEN 'HIGH'
        WHEN RATE <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
    SUB
ORDER BY
    ID