WITH RECURSIVE GENERATIONS AS (
    SELECT
        ID,
        1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        C.ID,
        P.GENERATION + 1
    FROM
        ECOLI_DATA C
    JOIN
        GENERATIONS P ON C.PARENT_ID = P.ID
)

SELECT
    COUNT(*) AS COUNT, GENERATION
FROM
    GENERATIONS
WHERE
    ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY
    GENERATION
ORDER BY
    GENERATION